#ifndef STAUTOARCHIVO_H_INCLUDED
#define STAUTOARCHIVO_H_INCLUDED

#define MAX_CARACT_AUTOARCHIVO_PATENTE 10
#define MAX_CARACT_AUTOARCHIVO_STANDARD 20
#define MAX_CARACT_AUTOARCHIVO_DNITITULAR 15

typedef struct stAutoArchivo {
	char patente[MAX_CARACT_AUTOARCHIVO_PATENTE];
	char marca[MAX_CARACT_AUTOARCHIVO_STANDARD];
	char modelo[MAX_CARACT_AUTOARCHIVO_STANDARD];
	int año;
	int kms;
	char dniTitular[MAX_CARACT_AUTOARCHIVO_DNITITULAR];
	float precioDeAdquisicion;
} AutoArchivo;


#endif // STAUTOARCHIVO_H_INCLUDED
