#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define MAX_CARACT_STRING 20
#define MAX_CARACT_STRING_DNI 10
#define START_INDEX 0
#define EXIT_VALUE 0

#define MAX_CARACT_AUTO_STANDARD 20
#define MAX_CARACT_AUTO_DNITITULAR 10

#define MAX_CARACT_PERSONA_STANDARD 20
#define MAX_CARACT_PERSONA_DNI 10

#define MAX_CARACT_USUARIO_STANDARD 20
#define MAX_CARACT_USUARIO_DNI 10

#define MAX_CARACT_VENTA_STANDARD 20
#define MAX_CARACT_VENTA_DNI 10

#define VALOR_REDIMENSIONAMIENTO_AUTO 2
#define VALOR_DIMENSIONAMIENTO_PERSONADINAMICA 2
#define VALOR_DIMENSIONAMIENTO_AUTODINAMICO 2
#define VALOR_DIMENSIONAMIENTO_USUARIODINAMICO 2
#define VALOR_DIMENSIONAMIENTO_VENTADINAMICA 2

#endif // CONSTANTS_H_INCLUDED
